config/routes.rb
ReporteFallasServicio::Application.routes.draw do
  resources :failing_services

end

app/models/failing_service.rb
class FailingService < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/failing_services_controller.rb
class FailingServicesController < ApplicationController
  before_action :set_failing_service, only: [:show, :edit, :update, :destroy]

  # GET /failing_services
  # GET /failing_services.json
  def index
    @failing_services = FailingService.all
  end

  # GET /failing_services/1
  # GET /failing_services/1.json
  def show
  end

  # GET /failing_services/new
  def new
    @failing_service = FailingService.new
  end

  # GET /failing_services/1/edit
  def edit
  end

  # POST /failing_services
  # POST /failing_services.json
  def create
    @failing_service = FailingService.new(failing_service_params)

    respond_to do |format|
      if @failing_service.save
        format.html { redirect_to @failing_service, notice: 'Failing service was successfully created.' }
        format.json { render action: 'show', status: :created, location: @failing_service }
      else
        format.html { render action: 'new' }
        format.json { render json: @failing_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /failing_services/1
  # PATCH/PUT /failing_services/1.json
  def update
    respond_to do |format|
      if @failing_service.update(failing_service_params)
        format.html { redirect_to @failing_service, notice: 'Failing service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @failing_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /failing_services/1
  # DELETE /failing_services/1.json
  def destroy
    @failing_service.destroy
    respond_to do |format|
      format.html { redirect_to failing_services_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_failing_service
      @failing_service = FailingService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def failing_service_params
      params.require(:failing_service).permit(:TicketNum, :TicketTitle, :AffectedService, :Priotiry, :GeneratedBy, :DateTicket, :ProblemDescriprion, :TicketHistory, :TimeOfSolution, :ProblemResolution)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/failing_services_helper.rb
module FailingServicesHelper
end

app/views/failing_services/_form.html.erb
<%= form_for(@failing_service) do |f| %>
  <% if @failing_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@failing_service.errors.count, "error") %> prohibited this failing_service from being saved:</h2>

      <ul>
      <% @failing_service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :TicketNum %><br>
    <%= f.number_field :TicketNum %>
  </div>
  <div class="field">
    <%= f.label :TicketTitle %><br>
    <%= f.text_field :TicketTitle %>
  </div>
  <div class="field">
    <%= f.label :AffectedService %><br>
    <%= f.text_field :AffectedService %>
  </div>
  <div class="field">
    <%= f.label :Priotiry %><br>
    <%= f.text_field :Priotiry %>
  </div>
  <div class="field">
    <%= f.label :GeneratedBy %><br>
    <%= f.text_field :GeneratedBy %>
  </div>
  <div class="field">
    <%= f.label :DateTicket %><br>
    <%= f.datetime_select :DateTicket %>
  </div>
  <div class="field">
    <%= f.label :ProblemDescriprion %><br>
    <%= f.text_area :ProblemDescriprion %>
  </div>
  <div class="field">
    <%= f.label :TicketHistory %><br>
    <%= f.text_area :TicketHistory %>
  </div>
  <div class="field">
    <%= f.label :TimeOfSolution %><br>
    <%= f.text_area :TimeOfSolution %>
  </div>
  <div class="field">
    <%= f.label :ProblemResolution %><br>
    <%= f.text_area :ProblemResolution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/failing_services/edit.html.erb
<h1>Editing failing_service</h1>

<%= render 'form' %>

<%= link_to 'Show', @failing_service %> |
<%= link_to 'Back', failing_services_path %>

app/views/failing_services/index.html.erb
<div id="TitlePage"><h1>Reportes de Falla de Servicios</h1></div>

<table>
  <thead>
    <tr>
      <th>Numero de Ticket</th>
      <th>Tituloe</th>
      <th>Servicio Afectado</th>
      <th>Prioridad</th>
      <th>Realizado por</th>
      <th>Fecha</th>
      <th>Problema</th>
      <th>Antecedentes</th>
      <th>Tiempo de Solucion</th>
      <th>Solucion del Problema</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @failing_services.each do |failing_service| %>
      <tr>
        <td><%= failing_service.TicketNum %></td>
        <td><%= failing_service.TicketTitle %></td>
        <td><%= failing_service.AffectedService %></td>
        <td><%= failing_service.Priotiry %></td>
        <td><%= failing_service.GeneratedBy %></td>
        <td><%= failing_service.DateTicket %></td>
        <td><%= failing_service.ProblemDescriprion %></td>
        <td><%= failing_service.TicketHistory %></td>
        <td><%= failing_service.TimeOfSolution %></td>
        <td><%= failing_service.ProblemResolution %></td>
        <td><%= link_to 'Show', failing_service %></td>
        <td><%= link_to 'Edit', edit_failing_service_path(failing_service) %></td>
        <td><%= link_to 'Destroy', failing_service, method: :delete, data: { confirm: 'Desea eleminiar el registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Failing service', new_failing_service_path %>

app/views/failing_services/new.html.erb
<h1>New failing_service</h1>

<%= render 'form' %>

<%= link_to 'Back', failing_services_path %>

app/views/failing_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticketnum:</strong>
  <%= @failing_service.TicketNum %>
</p>

<p>
  <strong>Tickettitle:</strong>
  <%= @failing_service.TicketTitle %>
</p>

<p>
  <strong>Affectedservice:</strong>
  <%= @failing_service.AffectedService %>
</p>

<p>
  <strong>Priotiry:</strong>
  <%= @failing_service.Priotiry %>
</p>

<p>
  <strong>Generatedby:</strong>
  <%= @failing_service.GeneratedBy %>
</p>

<p>
  <strong>Dateticket:</strong>
  <%= @failing_service.DateTicket %>
</p>

<p>
  <strong>Problemdescriprion:</strong>
  <%= @failing_service.ProblemDescriprion %>
</p>

<p>
  <strong>Tickethistory:</strong>
  <%= @failing_service.TicketHistory %>
</p>

<p>
  <strong>Timeofsolution:</strong>
  <%= @failing_service.TimeOfSolution %>
</p>

<p>
  <strong>Problemresolution:</strong>
  <%= @failing_service.ProblemResolution %>
</p>

<%= link_to 'Edit', edit_failing_service_path(@failing_service) %> |
<%= link_to 'Back', failing_services_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReporteFallasServicio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>